### ISSUE TITLE
Puppetexplorer: API Reverse Proxy TLS authentication

### ISSUE THREAD

**Issue by tobru** [vshn/puppet-in-docker#3]
The Puppetexplorer API reverse proxy connects to the unauthenticated port 8080 of the PuppetDB. This needs to be changed so it connects using the authenticated and secure port 8081.

**Comment by alskgj** [comment]
Puppetexplorer is not used at the moment and this issue is not needed anymore. We will solve this internally with VSHNOPS-1400.
